### ISSUE TITLE
Support for integrating SGP30 sensor

### ISSUE THREAD

**Issue by dod91** [xoblite/BreakoutGardener#1]
Hi there,
I'm looking into your repo since it's very interesting for reading data from different sensors.

I'm using the SGP30 sensor connected to Raspberry Pi 4 for reading air quality.
[Your code](https://github.com.cnpmjs.org/xoblite/BreakoutGardener/blob/ff5892ddd99db39b5b0cff6fb4b9dc5627ceffe7/modules/SGP30.js) works only the first time it gets executed, after that no devices are detected on the i2c bus.
By turning Raspberry off and on again it works but only once again. 

Pseudo code looks like this
```
open i2c bus
scan for devices
send init command to read air quality
send read command to read data from sensor
read data from sensor
close bus
```

Can you help me on this? 
Thank you

**Comment by dod91** [comment]
Nevermind, just solved the problem.
Seems like the scan operation was causing the issue, thank you anyway :)

**Comment by xoblite** [comment]
Hi dod91,

thanks for the feedback - of all the devices I've worked with so far, the SGP30 - while pretty cool otherwise! - indeed seems to be the one most sensitive to various factors, including bus capacitance, misc timing aspects, an implicit need for asynchronous polling, etc. In my experience, it became more reliable across certain types of application restarts (read: regular/crashes/etc) after I added the possibility to perform a I2C General Call "soft reset" prior to using it again. Previously, I did this only as a "clean up" measure upon exiting (see boolean setting resetI2CDevicesOnExit in Breakout_Gardener.js), but I have since added the possibility to perform this also on application startup (this newer version is not yet released on GitHub though).

[...] I see now that you have solved the issue though, but please don't hesitate to get back to me if you experience any further issues and/or have other feedback to share, including your overall experience of Breakout Gardener, any other suggestions, etc. Thanks!

BR//KHH

_PS. I should maybe also note that BG does not yet support the save/load baseline functionality of the SGP30, but that is something I may consider for a later release. Got some other stuff to focus on before that though... ;-)_

**Comment by dod91** [comment]
Hello xoblite,
thank you for your feedback on the SGP30 :)

I'll be more than happy to share additional feedback, appreciate your super fast response!
